### ISSUE TITLE
Chatbot "Hello World" utilizing Azure Functions

### ISSUE THREAD

**Issue by m4thfr34k** [AmericanRedCross/damage-assessment-bot#10]

**Comment by maxnorth** [comment]
Initial chatbot azure function implemented in PR #22. This has been tested against the local bot framework emulator, the web chat channel, and facebook. It is currently set up with only in-memory conversation state storage, still needs to be integrated with Cosmos.

**Comment by m4thfr34k** [comment]
This item is complete.
