### ISSUE TITLE
As a chatbot user, I need to input disaster assessment information in order to submit my report

### ISSUE THREAD

**Issue by m4thfr34k** [AmericanRedCross/damage-assessment-bot#125]
Description:

Acceptance Criteria:
- [ ] - form is implemented using adaptive cards
- [ ] - includes first time registration of the user, ie admin stack, and flow of submitting an individual form

Definition of Done:

**Comment by blueelvis** [comment]
@maxnorth - I have added the adaptive card generation for collecting the sector related information.
