### ISSUE TITLE
Create Cosmos DB with two collections

### ISSUE THREAD

**Issue by m4thfr34k** [AmericanRedCross/damage-assessment-bot#2]
RCDA Data (Azure Cosmos DB)
Bot Conversation State (Azure Cosmos DB)

**Comment by blueelvis** [comment]
@m4thfr34k - Cosmos DB Instance (Resource Name -- `EST1-HUM-CDB-BOT-DEV-01`) has been created with the following structure -

- Database Name -- `EST1-HUM-CDB-BOT-DEV-01`
    - Collection Name -- `rcda_data_dev`
    - Collection Name -- `rcda_bot_conversation_state_dev`


Can we close out this issue?

**Comment by m4thfr34k** [comment]
No PR associated. This is initial setup. Deployment scripts will come later.
