### ISSUE TITLE
As a volunteer, I want to ask the chatbot for help so it can guide me on how to submit a report.

### ISSUE THREAD

**Issue by m4thfr34k** [AmericanRedCross/damage-assessment-bot#39]
Description:

Acceptance Criteria:

Definition of Done:

**Comment by m4thfr34k** [comment]
This is regarding the user asking for help on how to submit a report. This is not the user story related to asking for help because the volunteer is in danger.

**Comment by m4thfr34k** [comment]
Need to discuss what level of detail of help is expected in order to develop help conversation flow charts.

**Comment by dalekunce** [comment]
I'd expect them to know a fair amount/be trained well enough for most things. The help can give just a list of potential commands (help, report, etc). I also think it should give just a little more context for what the potential responses mean. What does 1-5 mean for severity? I'd keep this as simple as possible with the idea we can always add more QnA style stuff into it later. Either via code or the MS QnA resources.
