### ISSUE TITLE
As a volunteer, I want the chatbot to confirm the admin stack I am reporting on

### ISSUE THREAD

**Issue by m4thfr34k** [AmericanRedCross/damage-assessment-bot#42]
Description:

**Acceptance Criteria:**
If the chatbot user has a previously submitted report, the chatbot asks if they are still reporting on that location, "Are you still reporting on x admin stack?". This data should be stored in 'session.userData'.
If the user says no to the above question, or does not have a saved location then the bot should ask them for the admin stack they are reporting on behalf of.
The bot will collect this information by showing them a series of adaptive cards with cascading dropdown selects.
The first card will have a dropdown containing a list of regions. The user must select one of these.
The next card will have a dropdown containing a list of districts within the selected region.
The last card will have a dropdown containing a list of townships within the selected district.
The final township they select will be the admin level they report on.

Definition of Done:

**Comment by danbjoseph** [comment]
this is important, in the Myanmar context (and likely other contexts) a single roving person or team may be tasked with reporting on multiple areas
