### ISSUE TITLE
As a volunteer, I want to chat with a chat bot to submit my damage assessment reports so that I don't have to write it down on a paper report to submit.

### ISSUE THREAD

**Issue by m4thfr34k** [AmericanRedCross/damage-assessment-bot#60]
Description:
Data collection only

Acceptance Criteria:

Definition of Done:

**Comment by maxnorth** [comment]
Closed, this was just for the first pass when we were using a call and response data collection model. Now that we are committed to the adaptive card forms approach via webchat, the work to implement this is tracked by #125
