### ISSUE TITLE
Segregate dialogs into separate files

### ISSUE THREAD

**Issue by m4thfr34k** [AmericanRedCross/damage-assessment-bot#87]

**Comment by blueelvis** [comment]
@m4thfr34k @maxnorth This has been taken care of. Related branch/commit containing separate dialogs -- https://github.com/AmericanRedCross/damage-assessment-bot/tree/help-dialogs

As part of this, following things have been tackled -
1. Separation of dialogs into separate files
2. Addition of Help related dialogs to each file
3. Addition of global chat helpers and dialogs
4. Added adaptive card functions to collect sector related information.
5. Researched to get a working Prompt for Adaptive Cards.

The integration/wiring up of these dialogs will be tackled in a separate task. Please let me know if this estimation doesn't look good :)
