### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/damage-assessment-bot#94]
- [ ] Document steps for development
- [ ] Document steps for production

**Comment by blueelvis** [comment]
@dalekunce - When you say document steps for production, do you mean the deployment steps across all the environments?

**Comment by dalekunce** [comment]
yes deployment stuff like ```npm install``` and any configuration that needs to happen.

**Comment by m4thfr34k** [comment]
Closing due to this being a duplicate of the linked stories. #23 #118
